version: "3"
name: app-web-exemple
services:
    web:
        image: nginx
        ports:
            - 3000:80
        networks:
            - net
        volumes:
            - ./src:/app
    db:
        image: mysql
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - net
        environment:
            - MYSQL_ROOT_PASSWORD=my-secure-pwd
volumes:
    db-data:
networks:
    net:
