version: '1.0'
services:
  dns:
    build: ./bind
    container_name: dns-server
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./bind/data/:/etc/bind/"
    networks:
      admin2:
        ipv4_address: 10.0.0.2
  nginx:
    image: nginx:latest
    container_name: web-server
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf:/etc/nginx
    networks:
      admin2:
        ipv4_address: 10.0.0.3
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mariadbtest
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mypass
    volumes:
      - /home/samaze123/mysql:/var/lib/mysql
    networks:
      admin2:
        ipv4_address: 10.0.0.4

networks:
  admin2:
    name: admin2
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
