version: '1.0'
services:
  dns:
    image: ubuntu/bind9:latest
    container_name: dns-server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./bind/:/etc/bind/"
    networks:
      admin2:
        ipv4_address: 10.0.0.2
  nginx:
    image: nginx:latest
    container_name: web-server
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./nginx:/etc/nginx
      - ./site1.conf:/etc/nginx/sites-enabled/site1.conf
      - ./site2.conf:/etc/nginx/sites-enabled/site2.conf
    networks:
      admin2:
        ipv4_address: 10.0.0.3

networks:
  admin2:
    name: admin2
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
