version: '3.9'
services:
  dns_server:
    build: ./resolver
    container_name: dns_server
    ports:
      - '5455:53/udp'
      - '5456:53/tcp'
    networks:
      my_network:
        ipv4_address: 172.20.0.10
        aliases:
          - ns1.woodytoys.test

  web_server:
    build: ./web
    container_name: web_server
    networks:
      my_network:
        ipv4_address: 172.20.0.11
        aliases:
          - www.woodytoys.test
    volumes:
      - ./web/site1:/var/www/site1
      - ./web/site2:/var/www/site2
      - ./web/site3:/var/www/site3
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: my_db
      DB_USERNAME: my_user
      DB_PASSWORD: my_password
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      my_network:
        ipv4_address: 172.20.0.14
        aliases:
          - mysql.woodytoys.test

  postfix_container:
    build: ./mail
    container_name: postfix_container
    ports:
      - '2526:25'
    networks:
      my_network:
        ipv4_address: 172.20.0.12
        aliases:
          - mail.woodytoys.test

  dovecot_container:
    build: ./dovecot
    container_name: dovecot_container
    ports:
      - '143:143'
      - '993:993'
    networks:
      my_network:
        ipv4_address: 172.20.0.13
        aliases:
          - dovecot.woodytoys.test

  user_container:
    build: ./user
    container_name: user_container
    command: tail -f /dev/null
    dns:
      - 172.20.0.10
    networks:
      my_network:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
