version: '1.0'
services:
  dmz_soa:
    build: ./dmz/dmz_soa
    container_name: dmz_soa
    dns:
      - 192.168.2.2
    networks:
      dmz:
        ipv4_address: 192.168.2.2
        aliases:
          - ns.l1-6.ephec-ti.be
  dmz_web:
    build: ./dmz/web
    container_name: dmz_web
    networks:
      dmz:
        ipv4_address: 192.168.2.3
    volumes:
      - ./dmz/web/site:/var/www/site
      - ./dmz/web/b2b:/var/www/b2b
      - ./dmz/web/erp:/var/www/erp
    env_file: ./dmz/web/env.list
    depends_on:
      - mysql

  sz_dns:
    build: ./sz/sz_dns
    container_name: sz_dns
    dns:
      - 192.168.1.2
      - 192.168.2.2
    ports:
      - 5353:53/tcp
      - 5353:53/udp
    networks:
      dmz:
        ipv4_address: 192.168.2.5
      sz:
        ipv4_address: 192.168.1.2
        aliases:
          - ns.internal.l1-6.ephec-ti.be
  dovecot:
    build: ./sz/dovecot
    container_name: dovecot
    ports:
      - '143'
      - '993'
    networks:
      sz:
        ipv4_address: 192.168.1.3
        aliases:
          - dovecot.internal.l1-6.ephec-ti.be
  mysql:
    build: ./sz/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./sz/mysql/env.list
    networks:
      sz:
        ipv4_address: 192.168.1.4
        aliases:
          - mysql.internal.l1-6.ephec-ti.be
      dmz:
        ipv4_address: 192.168.2.6
  user:
    build: ./users
    container_name: user
    command: tail -f /dev/null
    dns:
      - 192.168.1.2
    networks:
      users:
      sz:
        ipv4_address: 192.168.1.5

networks:
  dmz:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
  sz:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  users:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
