version: '1.0'
services:
  dns:
    build: ./bind
    container_name: dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./bind/data/:/etc/bind/"
    networks:
      admin2:
        ipv4_address: 10.0.0.2
  nginx:
    image: nginx:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf:/etc/nginx
    networks:
      admin2:
        ipv4_address: 10.0.0.3
  mariadb:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mariadbtest
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mypass
    volumes:
      - /home/samaze123/mysql:/var/lib/mysql
    networks:
      admin2:
        ipv4_address: 10.0.0.4
  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - "./nginx/html/site1:/var/www/html/site1"
    networks:
      admin2:
        ipv4_address: 10.0.0.5

networks:
  admin2:
    name: admin2
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
