version: '3.9'
services:
  resolver:
    build: ./resolver
    container_name: resolver
    ports:
      - '53/tcp'
      - '53/udp'
    networks:
      my_network:
        ipv4_address: 192.168.0.10
        aliases:
          - ns.internal.l1-6.ephec-ti.be
  soa_dmz:
    build: ./soa_dmz
    container_name: soa_dmz
    ports:
      - '53/tcp'
      - '53/udp'
    networks:
      my_network:
        ipv4_address: 192.168.0.20
        aliases:
          - ns.l1-6.ephec-ti.be

  web_server:
    build: ./web
    container_name: web_server
    networks:
      my_network:
        ipv4_address: 192.168.0.11
        aliases:
          - www.internal.l1-6.ephec-ti.be
    volumes:
      - ./web/site:/var/www/site
      - ./web/b2b:/var/www/b2b
      - ./web/erp:/var/www/erp
    env_file: ./web/env.list
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./mysql/env.list
    networks:
      my_network:
        ipv4_address: 192.168.0.14
        aliases:
          - mysql.internal.l1-6.ephec-ti.be

  postfix_container:
    build: ./mail
    container_name: postfix_container
    ports:
      - '25'
    networks:
      my_network:
        ipv4_address: 192.168.0.12
        aliases:
          - mail.internal.l1-6.ephec-ti.be

  dovecot_container:
    build: ./dovecot
    container_name: dovecot_container
    ports:
      - '143'
      - '993'
    networks:
      my_network:
        ipv4_address: 192.168.0.13
        aliases:
          - dovecot.internal.l1-6.ephec-ti.be

  user_container:
    build: ./user
    container_name: user_container
    command: tail -f /dev/null
    dns:
      - 192.168.0.10
    networks:
      my_network:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/20
          gateway: 192.168.0.1
