version: '1.0'
services:
  # sz_resolver:
  #   build: ./sz/resolver
  #   container_name: sz_resolver
  #   networks:
  #     sz:
  #       ipv4_address: 192.168.1.2
  # sz_soa:
  #   build: ./sz/sz_soa
  #   container_name: sz_soa
  #   networks:
  #     sz:
  #       ipv4_address: 192.168.1.3
  dns_internal:
    build: ./sz/dns_internal
    container_name: dns_internal
    dns:
      - 192.168.1.2
    networks:
      sz:
        ipv4_address: 192.168.1.2
  user:
    build: ./users
    container_name: user
    command: tail -f /dev/null
    dns:
      - 192.168.1.2
    networks:
      users:
      sz:

networks:
  dmz:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
  sz:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  users:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
